#version 0.0.2
#@edt M06 2018-2019
#LDAPserver edt.org
#-------------------
FROM fedora:27
RUN dnf -y install procps openldap-clients openldap-servers vim less tree nmap mlocate man iproute
RUN mkdir /opt/docker
COPY * /opt/docker/
RUN chmod +x /opt/docker/install.sh /opt/docker/startup.sh
CMD ["/opt/docker/startup.sh"]
WORKDIR /opt/docker
