#version: 0.0.2
#@edt M06 2018-2019
#ldapclient base edt.org
#----------------------
FROM fedora:27
LABEL author="@edt ASIX M06 Curs 2018-2019"
LABEL description="ldaphost ldapclient edt.org"
RUN dnf -y install openldap-clients procps less tree man telnet iproute
RUN mkdir /opt/docker
COPY * /opt/docker/
RUN cp /opt/docker/ldap.conf /etc/openldap/ldap.conf
WORKDIR /opt/docker
CMD ["/bin/bash"]
